theme: jekyll-theme-merlot
test:
  post:
    - mvn test
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
steps:
  - store_test_results:
      path: junit